import React from 'react';
import { Box, Typography } from '@mui/material';
import { PdfTheme } from './pdfTheme';

interface ReportFooterProps {
  totalCount: number;
  pdfTheme: PdfTheme;
}

const ReportFooter: React.FC<ReportFooterProps> = ({ totalCount, pdfTheme }) => {
  return (
    <Box sx={{ 
      mt: 'auto', 
      pt: 1, 
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center'
    }}>
      <Typography sx={{ color: pdfTheme.text, fontSize: '9px', fontWeight: 'bold' }}>
        Total No. of entries: {totalCount}
      </Typography>
      <Typography sx={{ color: pdfTheme.text, fontSize: '9px' }}>
        Generated by System
      </Typography>
    </Box>
  );
};

export default ReportFooter;
