import React from 'react';
import { Box, Typography } from '@mui/material';
import { PdfTheme } from './pdfTheme';

interface ReportInfoProps {
  generatedOn: string;
  generatedBy: string;
  pdfTheme: PdfTheme;
  duration?: string;
}

const ReportInfo: React.FC<ReportInfoProps> = ({ generatedOn, generatedBy, pdfTheme, duration }) => {
  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.25, alignItems: 'flex-end' }}>
      <Typography sx={{ color: pdfTheme.text, fontSize: '9px' }}>
        <Box component="span" sx={{ fontWeight: 'bold' }}>Generated On: </Box>
        {generatedOn}
      </Typography>
      <Typography sx={{ color: pdfTheme.text, fontSize: '9px' }}>
        <Box component="span" sx={{ fontWeight: 'bold' }}>Generated By: </Box>
        {generatedBy}
      </Typography>
      {duration && (
        <Typography sx={{ color: pdfTheme.text, fontSize: '9px' }}>
          <Box component="span" sx={{ fontWeight: 'bold' }}>Duration: </Box>
          {duration}
        </Typography>
      )}
    </Box>
  );
};

export default ReportInfo;
